// Auto-generated by deploy.js — DO NOT EDIT MANUALLY
// Network: localhost | Deployed: 2026-05-24T11:57:52.004Z

export const CONTRACT_ADDRESSES = {
  TicketNFT: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  TicketMarketplace: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
};

export const CHAIN_ID = 31337;
