// Auto-generated by deploy.js — DO NOT EDIT MANUALLY
// Network: localhost | Deployed: 2026-05-24T11:50:39.030Z

export const CONTRACT_ADDRESSES = {
  TicketNFT: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
  TicketMarketplace: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
};

export const CHAIN_ID = 31337;
