const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("\n🚀 BlockTicket Deployment");
  console.log("══════════════════════════════════════════");
  console.log(`📍 Network:   ${network.name}`);
  console.log(`👤 Deployer:  ${deployer.address}`);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`💰 Balance:   ${ethers.formatEther(balance)} MATIC\n`);

  // ── 1. Deploy TicketNFT ──────────────────────────────────────────────────
  console.log("📄 Deploying TicketNFT...");

  const TicketNFT = await ethers.getContractFactory("TicketNFT");
  const ticketNFT = await TicketNFT.deploy(
    "BlockTicket — Concert NFT",        // name
    "BTKTNFT",                           // symbol
    1000,                                // maxSupply
    ethers.parseEther("0.01"),           // ticketPrice (0.01 MATIC / ETH locally)
    110,                                 // resalePriceCap (110%)
    deployer.address                     // organizer
  );

  await ticketNFT.waitForDeployment();
  const nftAddress = await ticketNFT.getAddress();
  console.log(`✅ TicketNFT deployed:        ${nftAddress}`);

  // ── 2. Deploy TicketMarketplace ───────────────────────────────────────────
  console.log("\n📄 Deploying TicketMarketplace...");

  const TicketMarketplace = await ethers.getContractFactory("TicketMarketplace");
  const marketplace = await TicketMarketplace.deploy(
    nftAddress,   // NFT contract address
    2             // 2% platform fee
  );

  await marketplace.waitForDeployment();
  const marketplaceAddress = await marketplace.getAddress();
  console.log(`✅ TicketMarketplace deployed: ${marketplaceAddress}`);

  // ── 3. Activate sale on TicketNFT ─────────────────────────────────────────
  console.log("\n⚙️  Activating ticket sale...");
  await ticketNFT.toggleSale();
  console.log("✅ Sale is now ACTIVE");

  // ── 4. Save deployment info ───────────────────────────────────────────────
  const deploymentInfo = {
    network: network.name,
    chainId: (await ethers.provider.getNetwork()).chainId.toString(),
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    contracts: {
      TicketNFT: {
        address: nftAddress,
        maxSupply: 1000,
        ticketPrice: "0.01",
        resalePriceCap: 110,
      },
      TicketMarketplace: {
        address: marketplaceAddress,
        platformFeePercent: 2,
      },
    },
  };

  // Save to blockchain/deployments/
  const deployDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deployDir)) fs.mkdirSync(deployDir, { recursive: true });

  const deployFile = path.join(deployDir, `${network.name}.json`);
  fs.writeFileSync(deployFile, JSON.stringify(deploymentInfo, null, 2));
  console.log(`\n💾 Deployment saved: deployments/${network.name}.json`);

  // ── 5. Copy ABIs + addresses to frontend ──────────────────────────────────
  console.log("\n📋 Copying ABIs to frontend...");

  const frontendContractsDir = path.join(
    __dirname,
    "../../src/contracts"
  );
  if (!fs.existsSync(frontendContractsDir)) {
    fs.mkdirSync(frontendContractsDir, { recursive: true });
  }

  // Copy TicketNFT ABI
  const nftArtifact = require("../artifacts/contracts/TicketNFT.sol/TicketNFT.json");
  fs.writeFileSync(
    path.join(frontendContractsDir, "TicketNFT.json"),
    JSON.stringify({ abi: nftArtifact.abi }, null, 2)
  );

  // Copy TicketMarketplace ABI
  const marketArtifact = require("../artifacts/contracts/TicketMarketplace.sol/TicketMarketplace.json");
  fs.writeFileSync(
    path.join(frontendContractsDir, "TicketMarketplace.json"),
    JSON.stringify({ abi: marketArtifact.abi }, null, 2)
  );

  // Write addresses.js for frontend
  const addressesContent = `// Auto-generated by deploy.js — DO NOT EDIT MANUALLY
// Network: ${network.name} | Deployed: ${new Date().toISOString()}

export const CONTRACT_ADDRESSES = {
  TicketNFT: "${nftAddress}",
  TicketMarketplace: "${marketplaceAddress}",
};

export const CHAIN_ID = ${(await ethers.provider.getNetwork()).chainId};
`;
  fs.writeFileSync(
    path.join(frontendContractsDir, "addresses.js"),
    addressesContent
  );

  console.log("✅ ABIs copied to ticketer-app/src/contracts/");
  console.log("✅ addresses.js written\n");

  // ── 6. Summary ────────────────────────────────────────────────────────────
  console.log("══════════════════════════════════════════");
  console.log("🎉 Deployment Complete!");
  console.log("══════════════════════════════════════════");
  console.log(`  TicketNFT:        ${nftAddress}`);
  console.log(`  TicketMarketplace: ${marketplaceAddress}`);
  console.log(`  Ticket Price:     0.01 ETH/MATIC`);
  console.log(`  Max Supply:       1000`);
  console.log(`  Resale Cap:       110%`);
  console.log(`  Platform Fee:     2%`);
  console.log("══════════════════════════════════════════\n");
}

main().catch((error) => {
  console.error("❌ Deployment failed:", error);
  process.exitCode = 1;
});
